---

- hosts: all
  become: true
  tasks:

# Installation in Ubuntu/Debian Distribution
       
        # Update repo index & Install apache2 and php package for Ubuntu
  - name: install apache package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

# Installation in Redhat Distribution
       
        # Update repo index & Install apache2 package and php package for CentOS
  - name: Install apache package
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Redhat", "CentOS"]
     #When: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"
